git clone https://github.com/Hellio404/Get_Next_Line_Tester;
git clone https://github.com/Mazoise/42TESTERS-GNL;
git clone https://github.com/charMstr/GNL_lover;
git clone https://github.com/mrjvs/42cursus_gnl_tests;
git clone https://github.com/lgrellie/gnl_tester;
norminette ../get_*;
cd ..;
cp ../get* .;
cd 42TESTERS-GNL;
bash all_tests_with_bonus.sh;
bash runSTDIN+LEAKS.sh;
cd ..;
cp ../get* GNL_lover/copy_in_here_GNL_files/;
cd GNL_lover;
./GNL_lover.sh;
cd copy_in_here_GNL_files;
rm get_next_line.c get_next_line_bonus.c get_next_line_utils.c get_next_line_utils_bonus.c get_next_line.h get_next_line_bonus.h;
cd ..;
sleep 2;
cd ..;
cp Makefile 42cursus_gnl_tests/
cd 42cursus_gnl_tests;
make;
cd ../gnl_tester;
rm get_next_line.c get_next_line_bonus.c get_next_line_utils.c get_next_line_utils_bonus.c get_next_line.h get_next_line_bonus.h;
cp ../get* .;
echo "buffer 1 : ";
./run_tests.sh 1;
echo "buffer 2 : ";
./run_tests.sh 2;
echo "buffer 3 : ";
./run_tests.sh 3;
echo "buffer 4 : ";
./run_tests.sh 4;
echo "buffer 5 : ";
./run_tests.sh 5;
echo "buffer 7 : ";
./run_tests.sh 7;
echo "buffer 8 : ";
./run_tests.sh 8;
echo "buffer 1000 : ";
./run_tests.sh 1000;
echo "buffer 100000 : ";
./run_tests.sh 100000;
echo "buffer 1000000 : ";
./run_tests.sh 1000000;
echo "buffer 10000000 : ";
./run_tests.sh 10000000;
rm get_next_line.c get_next_line_bonus.c get_next_line_utils.c get_next_line_utils_bonus.c get_next_line.h get_next_line_bonus.h;
cd ../Get_Next_Line_Tester;
bash run.sh;
